spring:
  application:
    name: rate-printer
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_CONNECT_STRING:localhost:2181}
      discovery:
        enabled: true
        register: false

grpc:
  client:
    currency-rate-provider:
      address: discovery:///currency-rate-provider
      negotiationType: plaintext
      defaultLoadBalancingPolicy: round_robin
