spring:
  application:
    name: currency-rate-provider
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_CONNECT_STRING:localhost:2181}
      discovery:
        enabled: true
        register: true
        instance-port: ${grpc.server.port}

grpc:
  server:
    port: ${GRPC_PORT:9090}
