// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rates.proto

// Protobuf Java Version: 3.25.3
package com.example.rates;

public interface RateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rates.RateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pair = 1;</code>
   * @return The pair.
   */
  java.lang.String getPair();
  /**
   * <code>string pair = 1;</code>
   * @return The bytes for pair.
   */
  com.google.protobuf.ByteString
      getPairBytes();

  /**
   * <code>double value = 2;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
