// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rates.proto

// Protobuf Java Version: 3.25.3
package com.example.rates;

public interface RateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rates.RateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * e.g. "USDRUB"
   * </pre>
   *
   * <code>string pair = 1;</code>
   * @return The pair.
   */
  java.lang.String getPair();
  /**
   * <pre>
   * e.g. "USDRUB"
   * </pre>
   *
   * <code>string pair = 1;</code>
   * @return The bytes for pair.
   */
  com.google.protobuf.ByteString
      getPairBytes();
}
