// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rates.proto

// Protobuf Java Version: 3.25.3
package com.example.rates;

public final class RatesProto {
  private RatesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rates_RateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rates_RateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rates_RateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rates_RateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013rates.proto\022\005rates\"\033\n\013RateRequest\022\014\n\004p" +
      "air\030\001 \001(\t\">\n\014RateResponse\022\014\n\004pair\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\001\022\021\n\ttimestamp\030\003 \001(\t2I\n\023Cur" +
      "rencyRateService\0222\n\007GetRate\022\022.rates.Rate" +
      "Request\032\023.rates.RateResponseB!\n\021com.exam" +
      "ple.ratesB\nRatesProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rates_RateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rates_RateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rates_RateRequest_descriptor,
        new java.lang.String[] { "Pair", });
    internal_static_rates_RateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rates_RateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rates_RateResponse_descriptor,
        new java.lang.String[] { "Pair", "Value", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
